---
#  Prepare the system
- name: Install dependencies and update apt cache (may take a bit)  # 1
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-requests
      - python3-docker
    state: present
    update_cache: true

#  Handle GPG keys
- name: Ensure keyrings directory exists                            # 2
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key                                     # 3
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

# Add Docker repository and install Docker
- name: Add Docker repository with signed-by                        # 4
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker                                              # 5
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is running                            # 5
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
