[load_balancer]
lb_node ansible_host=192.168.88.11 ansible_port=2222

[web_nodes]
web_node1 ansible_host=192.168.88.11 ansible_port=2223 web_port=8082 container_name=app-1
web_node2 ansible_host=192.168.88.11 ansible_port=2224 web_port=8083 container_name=app-2

[all:vars]
ansible_user=root
